Restore BehaviorSubject behavior for `HydratedSubject`
solid-software/hydrated pull request #25
Opened 2021-08-09 14:06 UTC by solid-yuriiprykhodko

2021-08-09 15:46 UTC, solid-vovabeloded requested changes
Great job, @solid-yuriiprykhodko! I've added a couple of suggestions here - please take a look. Overall, the code looks great - thanks.

2021-08-09 15:46 UTC, solid-vovabeloded commented on lib/src/hydrated.dart
> +    _subject.value = event;
Would it be a bit more readable?
```suggestion
    _subject.add(event);
```

2021-08-09 15:46 UTC, solid-vovabeloded commented on lib/src/hydrated.dart
> +            onListen: onListen, onCancel: onCancel, sync: sync)
Would it be great to add trailing commas for these constructors?

2021-08-09 15:46 UTC, solid-vovabeloded commented on test/hydrated_test.dart
> +  test('Listener BehaviorSubject behavior', () async {
What do you think about adding more context into the test description. For example: 
`HydratedSubject emits the latest value on listener added`.

2021-08-09 15:46 UTC, solid-vovabeloded commented on test/hydrated_test.dart
> +    final expectation = expectLater(
I think there is no sense in double-checking that the stream emits the latest value.

2021-08-09 15:46 UTC, solid-vovabeloded commented on test/hydrated_test.dart
> +    await completer.future;
It seems like we can use `subject.first` instead of this completer.

2021-08-10 13:48 UTC, solid-yuriiprykhodko commented on .github/workflows/flutter.yaml
> +        run: flutter test -r expanded
This makes CI log formatting a bit nicer -- we see all the test cases that were executed.

2021-08-10 13:49 UTC, solid-yuriiprykhodko commented on lib/src/hydrated.dart
> +import 'package:hydrated/src/utils/type_utils.dart';
Missed this in the previous PR -- the class was renamed, but the file wasn't.

2021-08-11 08:18 UTC, solid-vovabeloded submitted a review, later dismissed
LGTM, thanks @solid-yuriiprykhodko!

2021-08-12 06:54 UTC, merged