Migrate the project to use solid_lints
solid-software/hydrated pull request #31
Opened 2022-01-04 14:36 UTC by solid-yuriiprykhodko

2022-01-04 17:41 UTC, solid-yuriiprykhodko commented on test/hydrated_test.dart
>        });
This change comes from the fact that now we propagate all exceptions to the `HydratedSubject` Stream.

This gives user the freedom of choice when it comes to catching Errors.

2022-01-11 10:12 UTC, solid-software requested changes
Looks great - thanks @solid-yuriiprykhodko ! Added a few suggestion, let me know what you think. Overall very pleased with the changes made!

2022-01-11 10:12 UTC, solid-software commented on lib/src/key_value_store/shared_preferences_store.dart
>          _areTypesEqual<T, List<String>>() ||
```suggestion
        _isListOfStrings<T>() ||
```
to match, what do you think?

2022-01-11 10:12 UTC, solid-software commented on lib/src/key_value_store/store_error.dart
> +
```suggestion

```
probably should be removed?

2022-01-11 10:12 UTC, solid-software commented on test/shared_preferences_store_test.dart
> +          'it throws a StoreError', () {
This looks as interesting topic to discuss on whether we want to go that route

2022-01-17 19:20 UTC, solid-software approved these changes
LGTM - great job @solid-yuriiprykhodko !

2022-01-17 19:21 UTC, merged